image: ghcr.io/sairon/{arch}-base-python
build_from:
  aarch64: "ghcr.io/sairon/aarch64-base:"
  amd64: "ghcr.io/sairon/amd64-base:"
cosign:
  base_identity: https://github.com/sairon/docker-base/.*
  identity: https://github.com/sairon/docker-base/.*
args:
  PYTHON_VERSION: "3.13.12"
  PIP_VERSION: "25.3"
  CERT_IDENTITY: thomas@python.org
  CERT_OIDC_ISSUER: https://accounts.google.com
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/sairon/docker-base
